#!/bin/sh
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# Invoke the "rush lint-staged" and "rush prettier" custom commands to lint and reformat files whenever they
# are committed. The commands is defined in common/config/rush/command-line.json
# and uses the "rush-prettier" autoinstaller.
node common/scripts/install-run-rush.js lint-staged && node common/scripts/install-run-rush.js prettier || exit $?